### PR TITLE
Eleventy fixes

### PR DESCRIPTION
**Pull request by steverydz**
## Done

- Fixed global nav js being ignored in build
- Fixed site metadata not having values
- Replaced head and footer with includes 

## QA

- Run the site with `dotrun`
- Check that the page title shows in the browser tab
- Check that the global nav loads
- Check that the html `head` content is in the source
- Check that the footer is present on the page

### CODE REVIEW

**Comment by steverydz** [comment]
@nottrobin regarding our brief discussion on the use of partials for the head and footer earlier, I personally don't mind either way. I switched to the partial because it was there and assumed that it was intended to be used.

**Comment by nottrobin** [comment]
@steverydz did I accidentally leave the footer one in or something? I meant to remove them both.

Basically, I don't think splitting code up and keeping it in multiple places is useful in and of itself. In general, it's much easier to open a single file and find what you need in it than have to keep switching around between files. And in this case I really don't find the header and footer to even make the `default.html` any less easy to read.

If you're trying to debug an app that's new to you, you'll start from the entry template and then keep following `layout: ` and `{{ include }}` statements until you find your code. We would be kind to posterity if we reduce the number of jumps they have to make to find what they're looking for. As in, by not creating file structures that are unnecessarily deep.

Therefore, the point of creating include template files is purely for keeping code DRY, not for any other purpose. So we should totally create a `footer.html` as soon as, but not until, the code in that file is used in more than one place.

**Comment by steverydz** [comment]
@nottrobin both `head.html` and `footer.html` were in the project which is why I assumed they were meant to be there. Either way, I've removed them from this PR.

**Comment by nottrobin** [comment]
Understood, thanks. Sorry for not removing them properly.

**Comment by nottrobin** [comment]
@steverydz let me know if you need help to fix the CI errors.

**Comment by steverydz** [comment]
@nottrobin I can't see any difference between your branch and this one that would affect the github actions?

**Comment by nottrobin** [comment]
@steverydz the two `run` scripts broke because you deleted the last file in `src/js`, so that directory no longer exists. Now the docker image needs to be updated to create `src/js` before trying to copy global-nav.js into it.

lint-nginx is my fault and I'm still working on fixing that.

**Comment by nottrobin** [comment]
@steverydz I'll fix it my side

**Pull request merged**
